steps:
#printing the present working directory
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pwd'

      
options:
    substitution_option: 'ALLOW_LOOSE'
    logging: CLOUD_LOGGING_ONLY 
