steps:
#printing the present working directory
  - name: 'gcr.io/cloud-building/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pwd'
#printing the date
  - name: 'gcr.io/cloud-building/gcloud'
    entrypoint: 'bash'
      - '-c'
      - 'date'
      
options:
    substitution_option: 'ALLOW_LOOSE'
    logging: CLOUD_LOGGING_ONLY 