spring:
  application:
    name: gateway-service

  cloud:
    discovery:
      enabled: true
#    gateway:
#      routes:
#        - id: cart
#          uri: lb://cart
#          predicates:
#            - Path=/cart/**
#        - id: product
#          uri: lb://product
#          predicates:
#            - Path=/products/**
#        - id: user
#          uri: lb://user
#          predicates:
#            - Path=/user/**

#secret key - should be encrypted
jwt:
  secret: QW5nZWxpbmFUZXJlc2FTYW1wbGVTZWNyZXRLZXlGb3JVc2VjYXNld2hpY2hzaG91bGRiZWdyZWF0ZXJ0aGFuNTIwYml0c2FuZCBoZW5jZSBtYWtpbmdpdGxlbmd0aHkK==
  #3 minutes validity
  token:
    validity: 180000

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
